# Generated by Django 5.0.1 on 2024-02-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_wastetypedetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastetypedetail',
            name='waste_type',
            field=models.CharField(default='plastic', max_length=20),
        ),
    ]
