name: Build and Deploy to Render

on:
  push:
    branches:
      - main # Replace with your default branch name if different

env:
  RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin


      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: aksourav/waste-management-api:latest
          build-args: |
            EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
            EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}
            POSTGRES_URL=${{ secrets.POSTGRES_URL }}

  deploy-to-render:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ env.MY_RENDER_SERVICE_ID }}
          api-key: ${{ env.MY_RENDER_API_KEY }}
        env:
          RENDER_SERVICE_ID: ${{ env.MY_RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ env.MY_RENDER_API_KEY }}
